### ISSUE TITLE
CW0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai181-pshenichnyuk#8]
Це контрольне питання ви отримали під час проведення Code Review вашого рішення на завдання лабораторної роботи № 0 (вступної), розпочатого вами після створення запиту Pull Request.
Правильну відповідь на запитання дозволять вам отримати додаткові 2 бали до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідь вкажіть у вигляді коментаря.

Запитання:
Відомо, що з серпня 2021 року GitHub-сервер замінив класичний процес аутентифікації через пароль на процес з використанням Token під час безпечного оновлення GitHub-репозиторію. Поясніть, будь ласка, чому так було зроблено?

**Comment by candyflip2001** [comment]
Це було зроблено для заміни процесу аутентифікації на процес авторизації, а саме заміни протоколу OpenID на OAuth. OpenID призначений для аутентифікації - тобто для того, щоб зрозуміти, що цей конкретний користувач є тим, ким представляється, тоді як OAuth є протоколом авторизації, тобто дозволяє видати права на дії, які користувач зможе виробляти в системі.

**Comment by oleksandrblazhko** [comment]
Оцінка = 2 бали
